export type TProduct = {
    id: number,
    refrence: string,
    name: string,
    description: string,
    category_name: string,
    price: string,
    superdiscount: boolean,
    discount: number,
    rating: number,
    colors: string[],
    comments_number: number,
    fast_delivery: boolean,
    product_image: string,
};
