import { TProduct } from '@/types/routes/global/product';

export const productSliderData: TProduct[] = [
  {
    id: 1,
    refrence: '/',
    name: 'ساعت هوشمند مدل Green Lion Ultra Active GNSW49',
    description: 'تست',
    category_name: 'نوکیا',
    price: '500000',
    superdiscount: false,
    discount: 50,
    rating: 4,
    colors: ['#377DFF', '#efefef', '#ABB4BC'],
    comments_number: 1,
    fast_delivery: true,
    product_image:
      'https://cdn.mobit.ir/get/mobit/product/20753/60d9df6fc03df.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 2,
    refrence: '/',
    name: 'ساعت هوشمند مدل Green Lion Ultra Active GNSW49',
    description: 'تست',
    category_name: 'نوکیا',
    price: '120000',
    superdiscount: true,
    discount: 0,
    rating: 4,
    comments_number: 0,
    colors: ['#ffffff', '#efefef'],
    fast_delivery: true,
    product_image:
      'https://cdn.mobit.ir/get/mobit/product/20753/60d9df6fc03df.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 3,
    refrence: '/',
    name: 'ساعت هوشمند مدل Green Lion Ultra Active GNSW49',
    description: 'تست',
    category_name: 'نوکیا',
    price: '120000',
    superdiscount: true,
    discount: 50,
    rating: 4,
    comments_number: 7,
    colors: ['#ffffff', '#efefef'],
    fast_delivery: true,
    product_image:
      'https://cdn.mobit.ir/get/mobit/product/20753/60d9df6fc03df.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 4,
    refrence: '/',
    name: 'ساعت هوشمند مدل Green Lion Ultra Active GNSW49',
    description: 'تست',
    category_name: 'نوکیا',
    price: '120000',
    superdiscount: true,
    discount: 10,
    rating: 4,
    comments_number: 1,
    colors: ['#ffffff', '#efefef'],
    fast_delivery: true,
    product_image:
      'https://cdn.mobit.ir/get/mobit/product/20753/60d9df6fc03df.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 5,
    refrence: '/',
    name: 'ساعت هوشمند مدل Green Lion Ultra Active GNSW49',
    description: 'تست',
    category_name: 'نوکیا',
    price: '120000',
    superdiscount: true,
    discount: 10,
    rating: 4,
    comments_number: 1,
    colors: ['#ffffff', '#efefef'],
    fast_delivery: true,
    product_image:
      'https://cdn.mobit.ir/get/mobit/product/20753/60d9df6fc03df.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 6,
    refrence: '/',
    name: 'ساعت هوشمند مدل Green Lion Ultra Active GNSW49',
    description: 'تست',
    category_name: 'نوکیا',
    price: '120000',
    superdiscount: true,
    discount: 10,
    rating: 4,
    comments_number: 1,
    colors: ['#ffffff', '#efefef'],
    fast_delivery: true,
    product_image:
      'https://cdn.mobit.ir/get/mobit/product/20753/60d9df6fc03df.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 7,
    refrence: '/',
    name: 'ساعت هوشمند مدل Green Lion Ultra Active GNSW49',
    description: 'تست',
    category_name: 'نوکیا',
    price: '120000',
    superdiscount: true,
    discount: 10,
    rating: 4,
    comments_number: 1,
    colors: ['#ffffff', '#efefef'],
    fast_delivery: true,
    product_image:
      'https://cdn.mobit.ir/get/mobit/product/20753/60d9df6fc03df.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 8,
    refrence: '/',
    name: 'ساعت هوشمند مدل Green Lion Ultra Active GNSW49',
    description: 'تست',
    category_name: 'نوکیا',
    price: '120000',
    superdiscount: true,
    discount: 10,
    rating: 4,
    comments_number: 1,
    colors: ['#ffffff', '#efefef'],
    fast_delivery: true,
    product_image:
      'https://cdn.mobit.ir/get/mobit/product/20753/60d9df6fc03df.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 9,
    refrence: '/',
    name: 'ساعت هوشمند مدل Green Lion Ultra Active GNSW49',
    description: 'تست',
    category_name: 'نوکیا',
    price: '120000',
    superdiscount: true,
    discount: 10,
    rating: 4,
    comments_number: 1,
    colors: ['#ffffff', '#efefef'],
    fast_delivery: true,
    product_image:
      'https://cdn.mobit.ir/get/mobit/product/20753/60d9df6fc03df.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 10,
    refrence: '/',
    name: 'ساعت هوشمند مدل Green Lion Ultra Active GNSW49',
    description: 'تست',
    category_name: 'نوکیا',
    price: '120000',
    superdiscount: true,
    discount: 10,
    rating: 4,
    comments_number: 1,
    colors: ['#ffffff', '#efefef'],
    fast_delivery: true,
    product_image:
      'https://cdn.mobit.ir/get/mobit/product/20753/60d9df6fc03df.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 11,
    refrence: '/',
    name: 'ساعت هوشمند مدل Green Lion Ultra Active GNSW49',
    description: 'تست',
    category_name: 'نوکیا',
    price: '120000',
    superdiscount: true,
    discount: 10,
    rating: 4,
    comments_number: 1,
    colors: ['#ffffff', '#efefef'],
    fast_delivery: true,
    product_image:
      'https://cdn.mobit.ir/get/mobit/product/20753/60d9df6fc03df.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 12,
    refrence: '/',
    name: 'ساعت هوشمند مدل Green Lion Ultra Active GNSW49',
    description: 'تست',
    category_name: 'نوکیا',
    price: '120000',
    superdiscount: true,
    discount: 10,
    rating: 4,
    comments_number: 1,
    colors: ['#ffffff', '#efefef'],
    fast_delivery: true,
    product_image:
      'https://cdn.mobit.ir/get/mobit/product/20753/60d9df6fc03df.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 13,
    refrence: '/',
    name: 'ساعت هوشمند مدل Green Lion Ultra Active GNSW49',
    description: 'تست',
    category_name: 'نوکیا',
    price: '120000',
    superdiscount: true,
    discount: 10,
    rating: 4,
    comments_number: 1,
    colors: ['#ffffff', '#efefef'],
    fast_delivery: true,
    product_image:
      'https://cdn.mobit.ir/get/mobit/product/20753/60d9df6fc03df.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 14,
    refrence: '/',
    name: 'ساعت هوشمند مدل Green Lion Ultra Active GNSW49',
    description: 'تست',
    category_name: 'نوکیا',
    price: '120000',
    superdiscount: true,
    discount: 10,
    rating: 4,
    comments_number: 1,
    colors: ['#ffffff', '#efefef'],
    fast_delivery: true,
    product_image:
      'https://cdn.mobit.ir/get/mobit/product/20753/60d9df6fc03df.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 15,
    refrence: '/',
    name: 'ساعت هوشمند مدل Green Lion Ultra Active GNSW49',
    description: 'تست',
    category_name: 'نوکیا',
    price: '120000',
    superdiscount: true,
    discount: 10,
    rating: 4,
    comments_number: 1,
    colors: ['#ffffff', '#efefef'],
    fast_delivery: true,
    product_image:
      'https://cdn.mobit.ir/get/mobit/product/20753/60d9df6fc03df.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 16,
    refrence: '/',
    name: 'ساعت هوشمند مدل Green Lion Ultra Active GNSW49',
    description: 'تست',
    category_name: 'نوکیا',
    price: '120000',
    superdiscount: true,
    discount: 10,
    rating: 4,
    comments_number: 1,
    colors: ['#ffffff', '#efefef'],
    fast_delivery: true,
    product_image:
      'https://cdn.mobit.ir/get/mobit/product/20753/60d9df6fc03df.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 17,
    refrence: '/',
    name: 'ساعت هوشمند مدل Green Lion Ultra Active GNSW49',
    description: 'تست',
    category_name: 'نوکیا',
    price: '120000',
    superdiscount: true,
    discount: 10,
    rating: 4,
    comments_number: 1,
    colors: ['#ffffff', '#efefef'],
    fast_delivery: true,
    product_image:
      'https://cdn.mobit.ir/get/mobit/product/20753/60d9df6fc03df.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 18,
    refrence: '/',
    name: 'ساعت هوشمند مدل Green Lion Ultra Active GNSW49',
    description: 'تست',
    category_name: 'نوکیا',
    price: '120000',
    superdiscount: true,
    discount: 10,
    rating: 4,
    comments_number: 1,
    colors: ['#ffffff', '#efefef'],
    fast_delivery: true,
    product_image:
      'https://cdn.mobit.ir/get/mobit/product/20753/60d9df6fc03df.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 19,
    refrence: '/',
    name: 'ساعت هوشمند مدل Green Lion Ultra Active GNSW49',
    description: 'تست',
    category_name: 'نوکیا',
    price: '120000',
    superdiscount: true,
    discount: 10,
    rating: 4,
    comments_number: 1,
    colors: ['#ffffff', '#efefef'],
    fast_delivery: true,
    product_image:
      'https://cdn.mobit.ir/get/mobit/product/20753/60d9df6fc03df.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 20,
    refrence: '/',
    name: 'ساعت هوشمند مدل Green Lion Ultra Active GNSW49',
    description: 'تست',
    category_name: 'نوکیا',
    price: '120000',
    superdiscount: true,
    discount: 10,
    rating: 4,
    comments_number: 1,
    colors: ['#ffffff', '#efefef'],
    fast_delivery: true,
    product_image:
      'https://cdn.mobit.ir/get/mobit/product/20753/60d9df6fc03df.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 21,
    refrence: '/',
    name: 'ساعت هوشمند مدل Green Lion Ultra Active GNSW49',
    description: 'تست',
    category_name: 'نوکیا',
    price: '120000',
    superdiscount: true,
    discount: 10,
    rating: 4,
    comments_number: 1,
    colors: ['#ffffff', '#efefef'],
    fast_delivery: true,
    product_image:
      'https://cdn.mobit.ir/get/mobit/product/20753/60d9df6fc03df.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
];
