export const staticCategoryData: any = [
  {
    id: String(1030),
    name: 'موبایل و تبلت',
    refrence: '/',
    children: [
      {
        id: String(1034),
        name: 'گوشی موبایل',
        featured: 1,
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [
          {
            id: String(1330),
            name: 'شیائومی',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobilephone/brand/xiaomi',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1331),
            name: 'سامسونگ',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobilephone/brand/samsung',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1332),
            name: 'اپل',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobilephone/brand/apple',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1333),
            name: 'هواوی',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobilephone/brand/huawei',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1334),
            name: 'نوکیا',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobilephone/brand/nokia',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1335),
            name: 'آنر',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobilephone/brand/honor',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1040),
            name: 'گوشی‌های ساده',

            sort: '-view',

            min_price: '100',
            max_price: '8000000',
            manual_link: '',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobilephone',
              params: {
                min_price: '100',
                max_price: '8000000',
                sort: '-view',
              },
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
        ],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(21) },
        apiLink: {
          path: 'search/digital-devices/mobile/mobilephone',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: false,
        isRoot: false,
      },
      {
        id: String(1176),
        name: 'لوازم جانبی موبایل',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [
          {
            id: String(1177),
            name: 'گلس گوشی موبایل',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobile-accessories/screen-protector',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1180),
            name: 'کیف و کاور گوشی',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobile-accessories/phone-case-and-cover',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1181),
            name: 'کابل و مبدل',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobile-accessories/cable-converter',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1182),
            name: 'کارت حافظه گوشی موبایل',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobile-accessories/memory-card',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1183),
            name: 'پایه نگهدارنده تبلت و گوشی',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobile-accessories/phoneholder',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1184),
            name: 'شارژر گوشی',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobile-accessories/mobile-tablet-charger',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1276),
            name: 'باتری گوشی',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobile-accessories/phone-battery',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1315),
            name: 'محافظ لنز دوربین گوشی موبایل',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobile-accessories/lens-screen-protector',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1316),
            name: 'قلم هوشمند',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobile-accessories/smartpen',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1347),
            name: 'کیف و کاور هندزفری',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobile-accessories/handsfree-case',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
        ],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(31) },
        apiLink: {
          path: 'search/digital-devices/mobile/mobile-accessories',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: false,
        isRoot: false,
      },
      {
        id: String(1179),
        name: 'هدفون،هدست،هندزفری',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(35) },
        apiLink: {
          path: 'search/digital-devices/mobile/mobile-accessories/headphones-headset-handsfree',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
      {
        id: String(1178),
        name: 'پاور بانک (شارژر همراه)',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(9) },
        apiLink: {
          path: 'search/digital-devices/mobile/mobile-accessories/powerbank',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
      {
        id: String(1199),
        name: 'تبلت',
        featured: 1,
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(24) },
        apiLink: {
          path: 'search/digital-devices/tablets-readers/tablet',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
    ],
    apiLink: {
      path: 'category/digital-devices/mobile',
      params: { sort: '-view' },
      isManual: false,
    },
    picture_link:
      'https://cdn.mobit.ir/get/mobit/menu/1030/60c6fb27448bb.svg?inline=1',
    isRoot: true,
    category: {
      id: String(20),
      category_name: 'موبایل',
      category_name_en: 'Mobile',
      slug: 'mobile',
      short_name: 'موبایل | خرید انواع گوشی و لوازم جانبی برندهای مختلف ',
      show_latin_name: 1,
      is_main: 0,
      index_to_cart: 0,
      for_kerman: 0,
      show_app: 0,
      show_in_category_mobile: 1,
      selected: 0,
      iconSrc:
        'https://cdn.mobit.ir/get/mobit/category/20/38370661936.png?inline=1',
      paybuyIconSrc: '',
      src: 'https://cdn.mobit.ir/get/mobit/category/20/6273692870a20.webp?inline=1',
      hierarchicalSlug: '/digital-devices/mobile',
      pageTitle: 'قیمت موبایل ⚡ (04 دی) + خرید اینترنتی - مبیت',
      routePage: 'category',
      color: null,
      isRoot: false,
    },
  },
  {
    id: String(1381),
    name: 'لوازم جانبی موبایل',
    refrence: '/',
    children: [
      {
        id: String(1382),
        name: 'برند گوشی',
        min_price: null,
        max_price: null,
        manual_link:
          'https://www.mobit.ir/cute-category-search/accessories?sort=-created',
        refrence: '/',
        children: [
          {
            id: String(1383),
            name: 'لوازم جانبی اپل',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'cute-category/accessories/apple-phone-accesories',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1384),
            name: 'لوازم جانبی سامسونگ',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'cute-category/accessories/samsung-accessories',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1385),
            name: 'لوازم جانبی شیائومی',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'cute-category/accessories/xiaomi-mobile-phone-accessories',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1386),
            name: 'لوازم جانبی هوآوی و آنر',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'cute-category/accessories/huawei-accessories',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1387),
            name: 'لوازم جانبی نوکیا',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'cute-category/accessories/nokia-phone-accesories',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1388),
            name: 'لوازم جانبی جی پلاس',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'cute-category/accessories/g-plus-mobile-phone-accessories',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
        ],
        menuImages: [],
        link: 'https://www.mobit.ir/cute-category-search/accessories?sort=-created',
        apiLink: {
          path: 'https://www.mobit.ir/cute-category-search/accessories?sort=-created',
          params: [],
          isManual: true,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: false,
        isRoot: false,
      },
      {
        id: String(1389),
        name: 'دسته بندی محصولات',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [
          {
            id: String(1392),
            name: 'شارژر',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobile-accessories/mobile-tablet-charger',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1404),
            name: 'کابل و مبدل',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobile-accessories/cable-converter',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1393),
            name: 'پاوربانک',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobile-accessories/powerbank',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1397),
            name: 'باتری گوشی موبایل',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobile-accessories/phone-battery',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1405),
            name: 'کارت حافظه گوشی موبایل',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobile-accessories/memory-card',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1398),
            name: 'کاور و کیف گوشی موبایل',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobile-accessories/phone-case-and-cover',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1402),
            name: 'محافظ لنز گوشی موبایل',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobile-accessories/lens-screen-protector',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1406),
            name: 'پایه نگهدارنده گوشی موبایل',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobile-accessories/phoneholder',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1401),
            name: 'گلس و محافظ صفحه گوشی موبایل',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobile-accessories/screen-protector',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1390),
            name: 'هدفون و هندزفری',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobile-accessories/headphones-headset-handsfree',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1408),
            name: 'کیف و کاور هندزفری',

            sort: '-sell',

            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/mobile/mobile-accessories/handsfree-case',
              params: { sort: '-sell' },
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1395),
            name: 'اسپیکر بلوتوثی',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/laptop/laptop-accessories/speaker',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1396),
            name: 'ساعت هوشمند',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/smart-watch-wristband',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
        ],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(31) },
        apiLink: {
          path: 'search/digital-devices/mobile/mobile-accessories',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: false,
        isRoot: false,
      },
    ],
    apiLink: {
      path: 'category/digital-devices/mobile/mobile-accessories',
      params: [],
      isManual: false,
    },
    picture_link:
      'https://cdn.mobit.ir/get/mobit/menu/1381/6356488970ff0.webp?inline=1',
    isRoot: true,
    category: {
      id: String(31),
      category_name: 'لوازم جانبی موبایل',
      category_name_en: 'mobile accessories',
      slug: 'mobile-accessories',
      short_name: 'جانبی موبایل',
      show_latin_name: 1,
      is_main: 0,
      index_to_cart: 0,
      for_kerman: 0,
      show_app: 0,
      show_in_category_mobile: 1,
      selected: 1,
      iconSrc:
        'https://cdn.mobit.ir/get/mobit/category/31/628098868e2de.svg?inline=1',
      paybuyIconSrc: '',
      src: 'https://cdn.mobit.ir/get/mobit/category/31/62736baee6f4e.webp?inline=1',
      hierarchicalSlug: '/digital-devices/mobile/mobile-accessories',
      pageTitle: 'قیمت لوازم جانبی موبایل ⚡ (04 دی) + خرید اینترنتی - مبیت',
      routePage: 'category',
      color: null,
      isRoot: false,
    },
  },
  {
    id: String(1058),
    name: 'لپ تاپ و کامپیوتر',
    refrence: '/',
    children: [
      {
        id: String(1200),
        name: 'قطعات اصلی',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [
          {
            id: String(1201),
            name: 'پردازنده',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/computer-equipments/computer-devices/processor',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1202),
            name: 'مادربورد',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/computer-equipments/computer-devices/motherboard',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1203),
            name: 'رم کامپیوتر',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/computer-equipments/computer-devices/computer-ram',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1204),
            name: 'منبع تغذیه',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/computer-equipments/computer-devices/power-supply',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1205),
            name: 'کارت گرافیک',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/computer-equipments/computer-devices/graphic-card',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1206),
            name: 'کیس',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/computer-equipments/computer-devices/case',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1207),
            name: 'هارد دیسک',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/computer-equipments/computer-devices/internal-hard-disk',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1211),
            name: 'درایو نوری',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/computer-equipments/computer-devices/optical-drive',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1212),
            name: 'فن - خنک کننده',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/computer-equipments/computer-devices/cpu-cooling',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
        ],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(32) },
        apiLink: {
          path: 'search/digital-devices/computer-equipments/computer-devices',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: false,
        isRoot: false,
      },
      {
        id: String(1215),
        name: 'جانبی کامپیوتر و لپ تاپ',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [
          {
            id: String(1216),
            name: 'کیبورد',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/computer-equipments/computer-devices/keyboard',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1217),
            name: 'ماوس',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/computer-equipments/computer-devices/mouse',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1220),
            name: 'ماوس پد',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/computer-equipments/computer-devices/mouse-pad',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1222),
            name: 'کیف هارد',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/computer-equipments/computer-devices/data-storage/external-hard-drive-case',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1223),
            name: 'کابل تبدیل و مبدل',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/computer-equipments/computer-devices/convert-cable',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1252),
            name: 'کیف و کوله',

            featured: 1,

            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/laptop/laptop-accessories/laptop-case',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1267),
            name: 'پایه خنک کننده',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/laptop/laptop-accessories/cooling-base',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1268),
            name: 'براکت هارد اینترنال',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/computer-equipments/computer-devices/internal-hard-drive-bracket',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1209),
            name: 'سایر قطعات جانبی',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/computer-equipments/computer-devices/computer-accessories',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
        ],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(27) },
        apiLink: {
          path: 'search/digital-devices/laptop/laptop-accessories',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: false,
        isRoot: false,
      },
      {
        id: String(1328),
        name: 'ذخیره ساز اطلاعات',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [
          {
            id: String(1213),
            name: 'حافظه اکسترنال',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/computer-equipments/computer-devices/data-storage/external-hard-drive',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
          {
            id: String(1208),
            name: 'حافظه SSD',
            refrence: '/',
            children: [],
            apiLink: {
              path: 'search/digital-devices/computer-equipments/computer-devices/data-storage/ssd',
              params: [],
              isManual: false,
            },
            picture_link: '',
            img_hover: '',
            isLeaf: true,
            isRoot: false,
          },
        ],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(2) },
        apiLink: {
          path: 'search/digital-devices/computer-equipments/computer-devices/data-storage',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: false,
        isRoot: false,
      },
      {
        id: String(1062),
        name: 'لپ تاپ',
        featured: 1,
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(26) },
        apiLink: {
          path: 'search/digital-devices/laptop/laptop-ultrabook',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
      {
        id: String(1277),
        name: 'کامپیوتر کوچک',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(846) },
        apiLink: {
          path: 'search/digital-devices/computer-equipments/mini-pc',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
      {
        id: String(1324),
        name: ' کامپیوتر All-in-One',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(420) },
        apiLink: {
          path: 'search/digital-devices/computer-equipments/computer-devices/allinonecomputers',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
      {
        id: String(1210),
        name: 'مانیتور',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(49) },
        apiLink: {
          path: 'search/digital-devices/computer-equipments/computer-devices/monitor',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
      {
        id: String(1218),
        name: 'اسپیکر',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(47) },
        apiLink: {
          path: 'search/digital-devices/laptop/laptop-accessories/speaker',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
      {
        id: String(1221),
        name: 'فلش مموری',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(3) },
        apiLink: {
          path: 'search/digital-devices/computer-equipments/computer-devices/data-storage/flash-memory',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
      {
        id: String(1326),
        name: 'تجهیزات شبکه',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(58) },
        apiLink: {
          path: 'search/digital-devices/computer-equipments/computer-devices/network-equipment',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
      {
        id: String(1327),
        name: 'دوربین مداربسته',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(675) },
        apiLink: {
          path: 'search/digital-devices/computer-equipments/computer-devices/network-equipment/network-system/cctv',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
      {
        id: String(1341),
        name: 'نرم افزار',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(343) },
        apiLink: {
          path: 'search/digital-devices/software',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
    ],
    apiLink: {
      path: 'category/digital-devices/laptop',
      params: { sort: '-view' },
      isManual: false,
    },
    picture_link:
      'https://cdn.mobit.ir/get/mobit/menu/1058/60c6fb4a6a949.svg?inline=1',
    isRoot: true,
    category: {
      id: String(22),
      category_name: 'لپ تاپ',
      category_name_en: 'Laptop',
      slug: 'laptop',
      short_name: 'قیمت انواع لپ تاپ گیمینگ، مالتی مدیا از برندهای مختلف',
      show_latin_name: 1,
      is_main: 0,
      index_to_cart: 0,
      for_kerman: 0,
      show_app: 0,
      show_in_category_mobile: 1,
      selected: 0,
      iconSrc:
        'https://cdn.mobit.ir/get/mobit/category/22/38481522397.png?inline=1',
      paybuyIconSrc: '',
      src: 'https://cdn.mobit.ir/get/mobit/category/22/60505055ef26b.png?inline=1',
      hierarchicalSlug: '/digital-devices/laptop',
      pageTitle: 'قیمت لپ تاپ ⚡ (04 دی) + خرید اینترنتی - مبیت',
      routePage: 'category',
      color: null,
      isRoot: false,
    },
  },
  {
    id: String(1078),
    name: 'گجت های هوشمند',
    refrence: '/',
    children: [
      {
        id: String(1310),
        name: 'ساعت هوشمند',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(63) },
        apiLink: {
          path: 'search/digital-devices/smart-watch-wristband/smart-watch',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
      {
        id: String(1311),
        name: 'مچ بند هوشمند',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(65) },
        apiLink: {
          path: 'search/digital-devices/smart-watch-wristband/smart-wristband',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
      {
        id: String(1312),
        name: 'لوازم جانبی شیائومی',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(779) },
        apiLink: {
          path: 'search/digital-devices/xiaomi-accessories',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
      {
        id: String(1380),
        name: 'لوازم جانبی مچ بند و ساعت هوشمند',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(66) },
        apiLink: {
          path: 'search/digital-devices/smart-watch-wristband/smart-wrist-accessories',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
    ],
    apiLink: {
      path: 'category/digital-devices/smart-watch-wristband',
      params: { sort: '-view' },
      isManual: false,
    },
    picture_link:
      'https://cdn.mobit.ir/get/mobit/menu/1078/60c6fb638d5d2.svg?inline=1',
    isRoot: true,
    category: {
      id: String(62),
      category_name: 'ساعت و مچ بند هوشمند',
      category_name_en: 'Smart watch wristband',
      slug: 'smart-watch-wristband',
      short_name: 'ساعت هوشمند',
      show_latin_name: 1,
      is_main: 0,
      index_to_cart: 0,
      for_kerman: 0,
      show_app: 0,
      show_in_category_mobile: 1,
      selected: 0,
      iconSrc:
        'https://cdn.mobit.ir/get/mobit/category/62/6260e2b01a51a.svg?inline=1',
      paybuyIconSrc: '',
      src: 'https://cdn.mobit.ir/get/mobit/category/62/625d25ce6191f.webp?inline=1',
      hierarchicalSlug: '/digital-devices/smart-watch-wristband',
      pageTitle: 'قیمت ساعت و مچ بند هوشمند ⚡ (04 دی) + خرید اینترنتی - مبیت',
      routePage: 'category',
      color: '',
      isRoot: false,
    },
  },
  {
    id: String(1082),
    name: 'لوازم صوتی و تصویری',
    refrence: '/',
    children: [
      {
        id: String(1307),
        name: 'تلویزیون',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(330) },
        apiLink: {
          path: 'search/digital-devices/audiovisual-equipment/television',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
      {
        id: String(1329),
        name: 'سینمای خانگی و ساندبار',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(417) },
        apiLink: {
          path: 'search/digital-devices/audiovisual-equipment/home-theater-sandbar',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
      {
        id: String(1314),
        name: 'لوازم جانبی صوتی و تصویری',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(422) },
        apiLink: {
          path: 'search/digital-devices/audiovisual-equipment/audio-video-accessories',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
      {
        id: String(1346),
        name: 'رادیو',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(886) },
        apiLink: {
          path: 'search/digital-devices/audiovisual-equipment/radio',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
    ],
    apiLink: {
      path: 'category/digital-devices/audiovisual-equipment',
      params: { sort: '-view' },
      isManual: false,
    },
    picture_link:
      'https://cdn.mobit.ir/get/mobit/menu/1082/60c6fb7cc5e41.svg?inline=1',
    isRoot: true,
    category: {
      id: String(329),
      category_name: 'لوازم صوتی و تصویری',
      category_name_en: 'audiovisual equipment',
      slug: 'audiovisual-equipment',
      short_name: 'خرید لوازم صوتی و تصویری',
      show_latin_name: 1,
      is_main: 0,
      index_to_cart: 0,
      for_kerman: 0,
      show_app: 0,
      show_in_category_mobile: 1,
      selected: 0,
      iconSrc:
        'https://cdn.mobit.ir/get/mobit/category/329/38550067145.png?inline=1',
      paybuyIconSrc: '',
      src: 'https://cdn.mobit.ir/get/mobit/category/329/38550067145.png?inline=1',
      hierarchicalSlug: '/digital-devices/audiovisual-equipment',
      pageTitle: 'قیمت لوازم صوتی و تصویری ⚡ (04 دی) + خرید اینترنتی - مبیت',
      routePage: 'category',
      color: '#3C80FF',
      isRoot: false,
    },
  },
  {
    id: String(1300),
    name: 'ماشین های اداری',
    refrence: '/',
    children: [
      {
        id: String(1301),
        name: 'پرینتر',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(60) },
        apiLink: {
          path: 'search/digital-devices/computer-equipments/computer-devices/printer',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
      {
        id: String(1308),
        name: 'پرینتر لیبل زن و لوازم جانبی',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(775) },
        apiLink: {
          path: 'search/digital-devices/office-machines/lable-printer-and-accesories',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
    ],
    apiLink: {
      path: 'category/digital-devices/office-machines',
      params: { sort: '-view' },
      isManual: false,
    },
    picture_link:
      'https://cdn.mobit.ir/get/mobit/menu/1300/60c6fb9be1687.svg?inline=1',
    isRoot: true,
    category: {
      id: String(771),
      category_name: 'ماشین های اداری',
      category_name_en: 'office machines',
      slug: 'office-machines',
      short_name: '',
      show_latin_name: 1,
      is_main: 1,
      index_to_cart: 0,
      for_kerman: 0,
      show_app: 0,
      show_in_category_mobile: 1,
      selected: 0,
      iconSrc:
        'https://cdn.mobit.ir/get/mobit/category/771/3857676240.png?inline=1',
      paybuyIconSrc: '',
      src: 'https://cdn.mobit.ir/get/mobit/category/771/3857676240.png?inline=1',
      hierarchicalSlug: '/digital-devices/office-machines',
      pageTitle: 'قیمت ماشین های اداری ⚡ (04 دی) + خرید اینترنتی - مبیت',
      routePage: 'category',
      color: '#3C80FF',
      isRoot: false,
    },
  },
  {
    id: String(1303),
    name: 'کنسول بازی',
    refrence: '/',
    children: [
      {
        id: String(1304),
        name: 'کنسول بازی خانگی',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(29) },
        apiLink: {
          path: 'search/digital-devices/game-console/home-game-console',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
      {
        id: String(1305),
        name: 'تجهیزات جانبی کنسول بازی',
        min_price: null,
        max_price: null,
        manual_link: '',
        refrence: '/',
        children: [],
        menuImages: [],
        link: { 0: 'products/main', category_id: String(30) },
        apiLink: {
          path: 'search/digital-devices/game-console/game-console-accessories',
          params: [],
          isManual: false,
        },
        picture_link: '',
        img_hover: '',
        isLeaf: true,
        isRoot: false,
      },
    ],
    apiLink: {
      path: 'category/digital-devices/game-console',
      params: { sort: '-view' },
      isManual: false,
    },
    picture_link:
      'https://cdn.mobit.ir/get/mobit/menu/1303/60c6fbb329e61.svg?inline=1',
    isRoot: true,
    category: {
      id: String(28),
      category_name: 'کنسول بازی',
      category_name_en: 'Game console',
      slug: 'game-console',
      short_name: 'کنسول بازی',
      show_latin_name: 1,
      is_main: 0,
      index_to_cart: 0,
      for_kerman: 0,
      show_app: 0,
      show_in_category_mobile: 1,
      selected: 0,
      iconSrc:
        'https://cdn.mobit.ir/get/mobit/category/28/60c7003a3bdbc.svg?inline=1',
      paybuyIconSrc: '',
      src: 'https://cdn.mobit.ir/get/mobit/category/28/60504c7759afa.png?inline=1',
      hierarchicalSlug: '/digital-devices/game-console',
      pageTitle: 'قیمت کنسول بازی ⚡ (04 دی) + خرید اینترنتی - مبیت',
      routePage: 'category',
      color: '#3C80FF',
      isRoot: false,
    },
  },
];
