import { TProduct } from '@/types/routes/global/product';

export const productSliderData: TProduct[] = [
  {
    id: 1,
    refrence: '/',
    name: 'گوشی موبایل ریلمی مدل C30s دو سیم کارت ظرفیت 64 گیگابایت و رم 3 گیگابایت',
    price: 2500000,
    superDiscount: true,
    discount: 50,
    rating: 4,
    colors: ['#377DFF', '#efefef', '#ABB4BC'],
    commentsLength: 1,
    fastDelivery: true,
    image:
      'https://cdn.mobit.ir/get/mobit/product/29404/64be2f7ee5533.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 2,
    refrence: '/',
    name: 'گوشی موبایل شیائومی مدل Redmi 12 دوسیم کارت ظرفیت 256 گیگابایت و 8 گیگابایت رم',
    price: 3200000,
    superDiscount: true,
    discount: 0,
    rating: 5,
    commentsLength: 7,
    colors: ['#000000'],
    fastDelivery: true,
    image:
      'https://cdn.mobit.ir/get/mobit/product/29502/64c897260030c.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 3,
    refrence: '/',
    name: 'اسپیکر قابل حمل انکر مدل Soundcore Mini 3 Pro',
    price: 1200000,
    superDiscount: true,
    discount: 20,
    rating: 4,
    commentsLength: 7,
    colors: ['#ff9900', '#1c4209'],
    fastDelivery: true,
    image:
      'https://cdn.mobit.ir/get/mobit/product/29591/64cf3786237b3.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 4,
    refrence: '/',
    name: 'ساعت هوشمند مدل HK8 Pro Max نسخه CHAT GPT',
    price: 80000,
    superDiscount: true,
    discount: 0,
    rating: 4,
    commentsLength: 0,
    colors: ['#55b72b'],
    fastDelivery: false,
    image:
      'https://cdn.mobit.ir/get/mobit/product/29826/64e9bb430fe31.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 5,
    refrence: '/',
    name: 'اسمارت واچ کیسلکت مدل Smart Calling Watch Kr Pro',
    price: 143000,
    superDiscount: true,
    discount: 20,
    rating: 1,
    commentsLength: 1,
    colors: ['#4a86e8'],
    fastDelivery: true,
    image:
      'https://cdn.mobit.ir/get/mobit/product/28558/639b554c6c0b5.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
  {
    id: 6,
    refrence: '/',
    name: 'هندزفری بی سیم کیو سی وای مدل MeloBuds ANC',
    price: 13000,
    superDiscount: true,
    discount: 80,
    rating: 5,
    commentsLength: 5,
    colors: ['#4a86e8'],
    fastDelivery: true,
    image:
      'https://cdn.mobit.ir/get/mobit/product/29820/64e8928ab5e3b.webp?x_oss_process=image/resize,w_180,h_180/quality,q_100&inline=1',
  },
];
